name: filtered push

on: 
  push:
    branches:
      - main
      - developer
    paths:
      - 'src/**'
      - '**.js'

jobs:
  sayhello:
    runs-on: ubuntu-latest
    steps:
      - name: for specific branches
        run: echo "hello,gtihub actions"

      - name: same like grettings
        run: echo "wellcome"
      

